[package]
name = "patricia-trie"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
serde = { version = "1", default-features = false, features = ["derive"] }
bincode = "1.3.3"

[dev-dependencies]
rand = "0.8.5"
